language: python
python:
  - "2.7"
  - "3.4"
install:
  - "pip install coveralls"
  - "pip install -e .[test]"
script: 
  - py.test --cov mapbox --cov-report term-missing
after_success:
  - coveralls
sudo: false
